apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bind.yaml
configMapGenerator:
  - name: bind-zone
    namespace: bind
    files:
      - starnix.net.zone
    options:
      disableNameSuffixHash: true
